name: 'Continuous Integration'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2.4.0'
        with:
          node-version: '14.x'
          cache: 'npm'

      - name: 'Install'
        run: 'npm install'

      - run: 'npm run lint'
      - run: 'npm run build'
      - run: 'npm run test'
